[최민주] ADD : 장바구니 추가/수량 변경 API
wecode-bootcamp-korea/41-1st-Weat-backend pull request #17
Opened 2023-01-08 05:03 UTC by Judy-Choi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 장바구니 장바구니 추가/수량 변경 API (upsert)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 장바구니 추가(create) + 수량 변경(update) => upsert 로 하나로 구현

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 주말에도 열코딩하는 나 자신 제법 멋져요 😎

2023-01-09 04:50 UTC, Kang-kyunghun requested changes

2023-01-09 04:50 UTC, Kang-kyunghun commented on routes/cartRouter.js
> +router.post("/upsert", validateToken, cartController.upsertCart);
```suggestion
router.post("", validateToken, cartController.upsertCart);
```

2023-01-10 02:06 UTC, Kang-kyunghun requested changes

2023-01-10 02:06 UTC, Kang-kyunghun commented on models/cartDao.js
> +    error.statusCode = 500;
status code 수정해 주세요.

2023-01-10 02:06 UTC, Kang-kyunghun commented on models/cartDao.js
> +    error.statusCode = 500;
여기도 status code 수정해 주세요.

2023-01-10 02:06 UTC, Kang-kyunghun commented on routes/cartRouter.js
> +router.post("/upsert", validateToken, cartController.upsertCart);
리뷰 반영이 안 되었네요??

2023-01-10 03:59 UTC, Judy-Choi commented on models/cartDao.js
> +    error.statusCode = 500;
500 -> 400 으로 Dao 에러코드 일괄 수정했습니다 🫡

2023-01-10 06:05 UTC, Judy-Choi commented on routes/cartRouter.js
> +router.post("/upsert", validateToken, cartController.upsertCart);
작업 중간에 FE 요청으로 인해 merge main 을 했더니 수정한 코드가 날아간 것 같습니다... 😂
번거롭게 해 드려서 죄송합니다. 반영되지 않은 리뷰 내용 다시 반영해서 올리겠습니다!

2023-01-10 06:05 UTC, Judy-Choi commented on models/cartDao.js
> +    error.statusCode = 500;
🫡

2023-01-10 06:26 UTC, Judy-Choi commented
항상 피드백 꼼꼼히 주셔서 감사합니다 🥰
이번 PR은 정신이 없어서 누락한 점이 많아서 번거롭게 해 드려서 죄송합니다 😂

2023-01-10 06:27 UTC, Judy-Choi commented
프론트와 통신을 해 보니 장바구니에서 수량 추가를 해도 DB에 반영되지 않는 이슈가 있어 cartDao.js 의 장바구니 수량 쿼리 수정했습니다!

2023-01-10 07:20 UTC, Kang-kyunghun commented
고생하셨습니다~~ 👍

2023-01-10 07:20 UTC, merged